using OnlineAccountingApp.Application.Features.CompanyFeatures.UniformChartOfAccountFeature.GetList;
using OnlineAccountingApp.Framework.MedatR.GetById;

namespace OnlineAccountingApp.Application.Features.CompanyFeatures.UniformChartOfAccountFeature.GetById;

public sealed class GetUniformChartOfAccountByIdQuery : BaseGetByIdQuery<UniformChartOfAccountListItemDto>
{
}
