using OnlineAccountingApp.Framework.MedatR.GetById;

namespace OnlineAccountingApp.Application.Features.CompanyFeatures.UniformChartOfAccountFeature.GetById;

public sealed class GetUniformChartOfAccountByIdQueryValidator : BaseGetByIdQueryValidator<GetUniformChartOfAccountByIdQuery>
{
}
