using OnlineAccountingApp.Framework.MedatR.Delete;

namespace OnlineAccountingApp.Application.Features.AppFeatures.MainRoleAndRoleRelationshipFeature.Delete;

public sealed class DeleteMainRoleAndRoleRelationshipCommandValidator : BaseDeleteCommandValidator<DeleteMainRoleAndRoleRelationshipCommand>
{
}
