using OnlineAccountingApp.Framework.MedatR.Delete;

namespace OnlineAccountingApp.Application.Features.CompanyFeatures.UniformChartOfAccountFeature.Delete;

public sealed class DeleteUniformChartOfAccountCommandValidator : BaseDeleteCommandValidator<DeleteUniformChartOfAccountCommand>
{
}
