using OnlineAccountingApp.Framework.MedatR.GetList;

namespace OnlineAccountingApp.Application.Features.AppFeatures.MainRoleAndRoleRelationshipFeature.GetMainRoleAndRoleRelationships;

public sealed class GetMainRoleAndRoleRelationshipsQueryValidator : BaseGetListQueryValidator<GetMainRoleAndRoleRelationshipsQuery>
{
}
