using OnlineAccountingApp.Framework.MedatR.Delete;

namespace OnlineAccountingApp.Application.Features.AppFeatures.MainRoleAndUserRelationshipFeature.Delete;

public sealed class DeleteMainRoleAndUserRelationshipCommandValidator : BaseDeleteCommandValidator<DeleteMainRoleAndUserRelationshipCommand>
{
}
